"""Models for the Instagram carousel presentation layer.

Carousel-specific fields generated by instagram_carousel_agent, separate from
the format-agnostic ArticleFullAnalysis.
"""
from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field, field_validator


class Hook(BaseModel):
    topic: str
    sub_topic: str
    headline: str
    context_line: str
    sub_topic_alt: list[str] = Field(default_factory=list)  # menu of alt hook questions (render-ignored; paste to swap)


class Interest(BaseModel):
    why_read: str
    pull_quote: str | None = None
    next_slide_hook: str


class CarouselGoFurtherItem(BaseModel):
    title: str
    source: str
    media_type: Literal["article", "report", "book", "documentary", "film", "serie", "video", "podcast", "academic_paper", "other"]
    category: Literal["deep_dive", "question_answer"]
    url: str | None = None
    duration_minutes: int | None = None
    why_explore: str
    cta_question_index: int | None = None


class PostReadingQuestion(BaseModel):
    id: str = ""
    question: str
    type: Literal["article_quality", "topic_substance", "reader_bias", "blind_spot"]


class CTA(BaseModel):
    title: str = ""   # punchy closing headline (≤10 words) that echoes the verdict's thesis
    engagement_sentence: str
    engagement_sentence_alt: list[str] = Field(default_factory=list)  # menu of alt closing questions (render-ignored)
    post_reading_questions: list[PostReadingQuestion]


class WatchOutItem(BaseModel):
    label: str   # short French descriptor, e.g. "Source unique", "Méthodologie", "Droit de réponse"
    text: str    # ≤15 words — the alert itself, no article quotes


class StrengthItem(BaseModel):
    label: str   # short French descriptor, e.g. "Exactitude factuelle", "Équité de traitement"
    text: str    # ≤15 words — what the article does well, no article quotes, no confidence/node ids


class Lens(BaseModel):
    id: str        # canonical lens id (see agent/lenses.py), e.g. "chiffres"
    name: str      # display name, e.g. "Chiffres sans base"
    question: str  # the always-ask question, ≤12 words


class ReadingBeat(BaseModel):
    moment: str    # ≤10 words — where we are in the article (reading order)
    quote: str     # verbatim anchor from the article
    lens_ref: str  # a canonical lens id (see agent/lenses.py), e.g. "chiffres"
    note: str      # ≤20 words — the CHALLENGE: what to look for (imperative/question), no verdict
    answer: str = ""  # ≤35 words — the REVEAL: what one finds / why it matters, no verdict
    factcheck: str = ""  # confidence_label of the matching claim (or "" if not a checkable fact)
    # candidate-pool fields (for manual cherry-picking; not rendered except `selected`)
    selected: bool = True   # render this beat as a moment slide (default True → old extracts keep working)
    theme: str = ""         # editor aid — the dimension this beat covers (carbone, faune, régulation…)
    centrality: int = 0     # editor aid — importance 1–5 (0 = unset)
    kind: str = ""          # editor aid — fait | biais | enjeu | statistique | affirmation
    rationale: str = ""     # editor aid — one line on why this beat is worth a slide


class GlobalAnalysis(BaseModel):
    headline: str                        # ≤10 words — the "mise en perspective" invitation, neutral
    headline_alt: list[str] = Field(default_factory=list)  # menu of alt headlines (render-ignored; paste to swap)
    core_recap: list[str] = Field(default_factory=list)  # 2–3 items, ≤16 words — proportion/scale points


class KeyTakeaway(BaseModel):
    text: str
    selected: bool = True   # render on slide 8; the pool holds candidates you cherry-pick


class SteelMan(BaseModel):
    argument: str      # ≤18 words — the strongest objection to the article's thesis
    alternative: str   # ≤14 words — the conclusion that follows if it holds


class CarouselDisplay(BaseModel):
    """Condensed, carousel-ready display strings for the long format slides."""
    payoff: str              # ≤15 words — what the reader gets from this article
    framing: str             # ≤15 words — the article's angle in plain language
    why_selected: str        # ≤20 words — the editorial reason this article earned a decrypt
    selection_headline: str  # ≤12 words — punchy one-line "why we chose it" (slide 2 headline)
    selection_headline_alt: list[str] = Field(default_factory=list)  # menu of alt subtitles (render-ignored)
    ethics: str              # ≤12 words — explicit clean/not-clean statement
    pre_reading: list[str]   # exactly 2 items, ≤12 words each
    watch_out: list[WatchOutItem]  # exactly 2 items, ≤15 words each, no article quotes
    strengths: list[StrengthItem]  # exactly 2 items — the article's 2 strongest dimensions
    distill_points: list[str]  # exactly 3 items, ≤20 words each
    after_reading: list[str]   # exactly 3 items, ≤12 words each
    key_takeaways: list[KeyTakeaway] = Field(default_factory=list)  # candidate POOL; the `selected` ones (2–3) render on slide 8. Plain strings are coerced to selected takeaways (back-compat).
    blind_spots: list[str]   # exactly 2 items, ≤15 words each — what the article leaves out
    balance: list[str]       # exactly 2 items, ≤15 words each — calibrating note on the analysis limits
    # 4-act "lens to read with" fields — all defaulted so old extracts still load.
    lenses: list[Lens] = Field(default_factory=list)            # Act 2 — 2–3 selected
    reading_beats: list[ReadingBeat] = Field(default_factory=list)  # Act 3 — 2–3, reading order
    global_analysis: GlobalAnalysis | None = None              # Act 4 slide 07
    open_question: str = ""                                     # (legacy) — superseded by root_issue
    root_issue: str = ""                                        # Act 4 slide 08 — the deeper problematic the article raises
    steel_man: SteelMan | None = None                          # Act 4 slide 08 — strongest objection
    reperes_headline: str = ""   # slide 3 headline override; empty → "Avant de vous lancer."
    bilan_headline: str = ""     # slide 9 headline override; empty → "L'essentiel, et les bons réflexes."
    essentiel: list[str] = Field(default_factory=list)  # 3 slide-sized points — kept in the pipeline (not rendered), reserve for later
    essentiel_summary: str = ""  # ≤50 words — the neutral prose summary rendered on the "L'essentiel" slide (right after the hook)

    @field_validator("key_takeaways", mode="before")
    @classmethod
    def _coerce_key_takeaways(cls, v):
        """Accept a plain list of strings (old extracts / hand edits) and coerce
        each into a selected KeyTakeaway."""
        if isinstance(v, list):
            return [{"text": x} if isinstance(x, str) else x for x in v]
        return v


class InstagramCarouselPresentation(BaseModel):
    hook: Hook
    interest: Interest
    title_bullets: list[str] = Field(default_factory=list)
    chapo_bullets: list[str] = Field(default_factory=list)
    context_next_slide_hook: str
    watch_out_next_slide_hook: str
    forme_next_slide_hook: str
    biases_next_slide_hook: str
    engagement_question: str
    go_further: list[CarouselGoFurtherItem]
    cta: CTA
    display: CarouselDisplay


class InstagramCarouselDocument(BaseModel):
    """Output of the extractor: selected analysis nodes + carousel presentation layer."""
    analysis: "ArticleFullAnalysis"  # noqa: F821  (resolved at runtime)
    presentation: InstagramCarouselPresentation


from models.full_analysis import ArticleFullAnalysis  # noqa: E402
InstagramCarouselDocument.model_rebuild()
