"""Models for the Instagram carousel presentation layer.

Carousel-specific fields generated by instagram_carousel_agent, separate from
the format-agnostic ArticleFullAnalysis.
"""
from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field


class Hook(BaseModel):
    topic: str
    sub_topic: str
    headline: str
    context_line: str


class Interest(BaseModel):
    why_read: str
    pull_quote: str | None = None
    next_slide_hook: str


class CarouselGoFurtherItem(BaseModel):
    title: str
    source: str
    media_type: Literal["article", "report", "book", "documentary", "film", "serie", "video", "podcast", "academic_paper", "other"]
    category: Literal["deep_dive", "question_answer"]
    url: str | None = None
    duration_minutes: int | None = None
    why_explore: str
    cta_question_index: int | None = None


class PostReadingQuestion(BaseModel):
    id: str = ""
    question: str
    type: Literal["article_quality", "topic_substance", "reader_bias", "blind_spot"]


class CTA(BaseModel):
    title: str = ""   # punchy closing headline (≤10 words) that echoes the verdict's thesis
    engagement_sentence: str
    post_reading_questions: list[PostReadingQuestion]


class WatchOutItem(BaseModel):
    label: str   # short French descriptor, e.g. "Source unique", "Méthodologie", "Droit de réponse"
    text: str    # ≤15 words — the alert itself, no article quotes


class StrengthItem(BaseModel):
    label: str   # short French descriptor, e.g. "Exactitude factuelle", "Équité de traitement"
    text: str    # ≤15 words — what the article does well, no article quotes, no confidence/node ids


class Lens(BaseModel):
    id: str        # canonical lens id (see agent/lenses.py), e.g. "chiffres"
    name: str      # display name, e.g. "Chiffres sans base"
    question: str  # the always-ask question, ≤12 words


class ReadingBeat(BaseModel):
    moment: str    # ≤10 words — where we are in the article (reading order)
    quote: str     # verbatim anchor from the article
    lens_ref: str  # must equal one selected Lens.id
    note: str      # ≤25 words — what to notice / the check, no verdict
    factcheck: str = ""  # confidence_label of the matching claim (or "" if not a checkable fact)


class GlobalAnalysis(BaseModel):
    headline: str          # ≤10 words — balanced one-line read of the whole
    solid: list[str] = Field(default_factory=list)  # 1–2 items, ≤16 words — what the article validly establishes / does well
    mechanism: list[str]   # 1–2 items, ≤18 words each — how the article pushes / its method
    signature: str         # ≤15 words — neutral characterization of the piece


class SteelMan(BaseModel):
    argument: str      # ≤18 words — the strongest objection to the article's thesis
    alternative: str   # ≤14 words — the conclusion that follows if it holds


class CarouselDisplay(BaseModel):
    """Condensed, carousel-ready display strings for the long format slides."""
    payoff: str              # ≤15 words — what the reader gets from this article
    framing: str             # ≤15 words — the article's angle in plain language
    why_selected: str        # ≤20 words — the editorial reason this article earned a decrypt
    selection_headline: str  # ≤12 words — punchy one-line "why we chose it" (slide 2 headline)
    ethics: str              # ≤12 words — explicit clean/not-clean statement
    pre_reading: list[str]   # exactly 2 items, ≤12 words each
    watch_out: list[WatchOutItem]  # exactly 2 items, ≤15 words each, no article quotes
    strengths: list[StrengthItem]  # exactly 2 items — the article's 2 strongest dimensions
    distill_points: list[str]  # exactly 3 items, ≤20 words each
    after_reading: list[str]   # exactly 3 items, ≤12 words each
    key_takeaways: list[str] = Field(default_factory=list)  # exactly 2 items, ≤14 words — the article's most memorable CONTENT points (facts/ideas the reader learns), distinct from our critique. Default [] so pre-existing extracts still load.
    blind_spots: list[str]   # exactly 2 items, ≤15 words each — what the article leaves out
    balance: list[str]       # exactly 2 items, ≤15 words each — calibrating note on the analysis limits
    # 4-act "lens to read with" fields — all defaulted so old extracts still load.
    lenses: list[Lens] = Field(default_factory=list)            # Act 2 — 2–3 selected
    reading_beats: list[ReadingBeat] = Field(default_factory=list)  # Act 3 — 2–3, reading order
    global_analysis: GlobalAnalysis | None = None              # Act 4 slide 07
    open_question: str = ""                                     # (legacy) — superseded by root_issue
    root_issue: str = ""                                        # Act 4 slide 08 — the deeper problematic the article raises
    steel_man: SteelMan | None = None                          # Act 4 slide 08 — strongest objection


class InstagramCarouselPresentation(BaseModel):
    hook: Hook
    interest: Interest
    title_bullets: list[str] = Field(default_factory=list)
    chapo_bullets: list[str] = Field(default_factory=list)
    context_next_slide_hook: str
    watch_out_next_slide_hook: str
    forme_next_slide_hook: str
    biases_next_slide_hook: str
    engagement_question: str
    go_further: list[CarouselGoFurtherItem]
    cta: CTA
    display: CarouselDisplay


class InstagramCarouselDocument(BaseModel):
    """Output of the extractor: selected analysis nodes + carousel presentation layer."""
    analysis: "ArticleFullAnalysis"  # noqa: F821  (resolved at runtime)
    presentation: InstagramCarouselPresentation


from models.full_analysis import ArticleFullAnalysis  # noqa: E402
InstagramCarouselDocument.model_rebuild()
