"""Models for the newsletter presentation layer.

Newsletter-specific prose generated by newsletter_adapt_agent — the same beats as
the instagram_carousel_optimized deck, rendered as detailed paragraphs (plus a
"Pour aller plus loin" section), not slide fragments.
"""
from __future__ import annotations
from pydantic import BaseModel
from typing import Literal


class DecryptageItem(BaseModel):
    """One reading moment in the chronological "Au fil de la lecture" pass, in
    article order. Neutral: no fait/faille grade badge is rendered — `kind` and
    `presentation` are kept for schema compatibility but unused by the templates."""
    kind: Literal["fait", "faille"]   # unused by rendering — kept for compatibility
    quote: str          # the article sentence examined (verbatim, « … »)
    presentation: str   # unused by rendering — kept for compatibility
    reading: str        # our neutral critical reading — what to notice (2–4 sentences)
    clue: str | None = None   # ≤12 words — the transferable reflex, echoing a paired pre-reading reflex


class NewsletterSection(BaseModel):
    heading: str   # short French section title
    body: str      # a detailed paragraph — the finding explained, with the article's own words


class Resource(BaseModel):
    title: str
    source: str
    why: str            # 1–2 sentences — what it adds / why explore it
    type: str | None = None   # kind of resource — "étude", "documentaire", "livre", "rapport", "podcast", "article"…


class NewsletterPresentation(BaseModel):
    """Reader-facing newsletter prose, mirroring the optimized carousel beats.
    Structured bits (score, recommendation, for_whom) are read from the analysis."""
    subject: str                        # ≤12 words — email subject line
    preheader: str                      # ≤15 words — inbox preview
    intro: str                          # hook / central tension (3–4 sentences)
    why_selected: str                   # Pourquoi cet article — why we picked it (2–3 sentences)
    payoff: str                         # what the reader gains (2–3 sentences)
    context: str                        # Avant de lire — the backdrop (3–4 sentences)
    reflexes: list[str]                 # exactly 2 — reading reflexes to keep in mind
    decryptage: list[DecryptageItem]    # 4–6, article-ordered — Au fil de la lecture (neutral reading moments)
    strengths: list[NewsletterSection]  # 1–2 — Ce qui tient
    angles_morts: list[str]             # 2–3 — Angles morts & nuances
    wrap_up: str                        # neutral synthesis / prise de recul, no recommendation (2–3 sentences)
    go_further: list[Resource]          # 2–3 — Pour aller plus loin (resources)
    prolongements: list[NewsletterSection]  # exactly 2 — Prolonger la réflexion: steel_man + cui_bono
    open_question: str                  # closing provocation, from distill.open_question
    signoff: str                        # closing line / CTA


class NewsletterDocument(BaseModel):
    """Output of the newsletter extractor: the full analysis + the newsletter prose."""
    analysis: "ArticleFullAnalysis"  # noqa: F821  (resolved at runtime)
    presentation: NewsletterPresentation


from models.full_analysis import ArticleFullAnalysis  # noqa: E402

NewsletterDocument.model_rebuild()
