"""Models for the newsletter presentation layer.

Newsletter-specific prose generated by newsletter_adapt_agent — the long-form
prose render of the optimized carousel deck, expanded into detailed paragraphs
(not slide fragments), neutral (no grade/verdict). The arc mirrors the
carousel's four acts:

  Header/hook → Pourquoi cet article → Avant de vous lancer →
  Au fil de la lecture → Après la lecture (L'architecture de l'argument,
  À emporter, À vous de juger, Prolonger la réflexion) → signoff
"""
from __future__ import annotations
from pydantic import BaseModel
from typing import Literal


class DecryptageItem(BaseModel):
    """One reading moment in the chronological "Au fil de la lecture" pass, in
    article order. Neutral: no fait/faille grade badge is rendered — `kind` and
    `presentation` are kept for schema compatibility but unused by the templates."""
    kind: Literal["fait", "faille"]   # unused by rendering — kept for compatibility
    quote: str          # the article sentence examined (verbatim, « … »)
    presentation: str   # unused by rendering — kept for compatibility
    reading: str        # our neutral critical reading — what to notice (2–4 sentences)
    clue: str | None = None   # ≤12 words — the transferable reflex, echoing a paired pre-reading reflex


class Resource(BaseModel):
    title: str
    source: str
    why: str            # 1–2 sentences — what it adds / why explore it
    type: str | None = None   # kind of resource — "étude", "documentaire", "livre", "rapport", "podcast", "article"…


class Architecture(BaseModel):
    """L'architecture de l'argument — the reasoning spine + the keystone question
    (mirrors the carousel's global_analysis: core_recap = spine, headline = keystone)."""
    keystone: str          # the load-bearing question the whole thesis rests on (global_analysis.headline)
    spine: list[str]       # 3–5 — the argument spine, A→B→C (from core_recap)


class AEmporter(BaseModel):
    """À emporter — what to keep: the key takeaways + the critical-reading reflexes recap."""
    key_takeaways: list[str]       # 3–5 — À retenir (the article's load-bearing facts)
    reflexes_critiques: list[str]  # 3–5 — Les réflexes critiques (the reading lenses recap)


class AVousDeJuger(BaseModel):
    """À vous de juger — hand the reader the material, neutrally, and let them
    judge the TOPIC (never the article's quality or the author)."""
    enjeux: list[str]        # 1–3 — Les enjeux de fond (the deeper problematics)
    objections: list[str]    # 1–3 — Les objections les plus solides (steel-man counters)
    angles_morts: list[str]  # 2–3 — Angles morts & nuances (topic omissions; no quality verdict)
    questions: list[str]     # 1–2 — open reader questions from root_issue (no author criticism)


class NewsletterPresentation(BaseModel):
    """Reader-facing newsletter prose — the long-form prose render of the optimized
    carousel deck (same sections, same order, expanded; no grade/verdict)."""
    subject: str            # ≤12 words — email subject line
    preheader: str          # ≤15 words — inbox preview
    intro: str              # hook / central tension (3–4 sentences)
    # Pourquoi cet article
    selection_headline: str   # the subtitle — punchy one-line "why we chose it"
    why_selected: str         # why we picked it to decrypt, expanded (2–3 sentences)
    payoff: str               # what the reader gains (2–3 sentences)
    # Avant de vous lancer
    context: str              # Le contexte — the backdrop (3–4 sentences)
    reflexes: list[str]       # 4–6 — Les réflexes: reading lenses + questions
    # Au fil de la lecture
    decryptage: list[DecryptageItem]    # 4–6, article-ordered — neutral reading moments
    # Après la lecture — L'architecture de l'argument
    architecture: Architecture
    # Après la lecture — À emporter
    a_emporter: AEmporter
    # Après la lecture — À vous de juger
    verdict: AVousDeJuger
    # Après la lecture — Prolonger la réflexion
    cui_bono: str             # « À qui profite ce cadrage ? » — beneficiary + why the framing serves them
    go_further: list[Resource]  # 3–5 — Pour aller plus loin (folded into Prolonger la réflexion)
    # signoff
    signoff: str              # closing line — "On sélectionne. On éclaire. Vous jugez."


class NewsletterDocument(BaseModel):
    """Output of the newsletter extractor: the full analysis + the newsletter prose."""
    analysis: "ArticleFullAnalysis"  # noqa: F821  (resolved at runtime)
    presentation: NewsletterPresentation


from models.full_analysis import ArticleFullAnalysis  # noqa: E402

NewsletterDocument.model_rebuild()
