"""Models for the newsletter presentation layer.

Newsletter-specific prose generated by newsletter_adapt_agent — the same beats as
the instagram_carousel_optimized deck, rendered as detailed paragraphs (plus a
"Pour aller plus loin" section), not slide fragments.
"""
from __future__ import annotations
from pydantic import BaseModel


class NewsletterSection(BaseModel):
    heading: str   # short French section title (e.g. "Source unique", "Exactitude factuelle")
    body: str      # a detailed paragraph — the finding explained, with the article's own words


class FactCheckItem(BaseModel):
    claim: str          # the claim, quoted or closely paraphrased
    presentation: str   # how the article frames it (fait établi / attribué à une source / opinion)
    reading: str        # our critical reading — 2–3 sentences, what holds and what to recheck


class Resource(BaseModel):
    title: str
    source: str
    why: str            # 1–2 sentences — what it adds / why explore it


class NewsletterPresentation(BaseModel):
    """Reader-facing newsletter prose, mirroring the optimized carousel beats.
    Structured bits (score, recommendation, for_whom) are read from the analysis."""
    subject: str                        # ≤12 words — email subject line
    preheader: str                      # ≤15 words — inbox preview
    intro: str                          # hook / central tension (3–4 sentences)
    why_selected: str                   # Pourquoi cet article — why we picked it (2–3 sentences)
    payoff: str                         # what the reader gains (2–3 sentences)
    context: str                        # Avant de lire — the backdrop (3–4 sentences)
    reflexes: list[str]                 # exactly 2 — reading reflexes to keep in mind
    fact_check: list[FactCheckItem]     # 2–3 — Vérification des faits
    failles: list[NewsletterSection]    # exactly 2 — Les failles (detailed, with article words)
    strengths: list[NewsletterSection]  # 1–2 — Ce qui tient
    angles_morts: list[str]             # 2–3 — Angles morts & nuances
    verdict_line: str                   # Notre verdict, in prose (2–3 sentences)
    go_further: list[Resource]          # 2–3 — Pour aller plus loin
    signoff: str                        # closing line / CTA


class NewsletterDocument(BaseModel):
    """Output of the newsletter extractor: the full analysis + the newsletter prose."""
    analysis: "ArticleFullAnalysis"  # noqa: F821  (resolved at runtime)
    presentation: NewsletterPresentation


from models.full_analysis import ArticleFullAnalysis  # noqa: E402

NewsletterDocument.model_rebuild()
